### Получени еинформации о боте
GET https://platform-api.max.ru/me
Accept: application/json
Authorization: {{access_token}}


### Получение списка всех групповых чатов
GET https://platform-api.max.ru/chats
Authorization: {{access_token}}

### Получение обновлений
GET https://platform-api.max.ru/updates?marker=31975589
Authorization: {{access_token}}

### Получение подписок
GET https://platform-api.max.ru/subscriptions
Authorization: {{access_token}}

### Отправить сообщение пользователю
POST https://platform-api.max.ru/messages?user_id=138414350
Authorization: {{access_token}}
Content-Type: application/json

{
  "text": "Это сообщение с кнопкой-ссылкой",
  "attachments": [
    {
      "type": "inline_keyboard",
      "payload": {
        "buttons": [
          [
            {
              "type": "link",
              "text": "Откройте сайт ✅❌",
              "url": "https://max.ru"
            }
          ]
        ]
      }
    }
  ]
}
### Сообщение пользователю с клавиатурой
POST https://platform-api.max.ru/messages?user_id=6084416
Authorization: {{access_token}}
Content-Type: application/json

{
  "text": "Это сообщение с клавиатурой\nInline-клавиатура может иметь до 210 кнопок, сгруппированных в 30 рядов — до 7 кнопок в каждом\n(до 3, если это кнопки типа link, openapp, requestgeolocation или requestcontact).",
  "attachments": [
    {
      "type": "inline_keyboard",
      "payload": {
        "buttons": [
          [
            {
              "type": "callback",
              "text": "✅ Да",
              "payload": "yes"
            },
            {
              "type": "callback",
              "text": "❌ Нет",
              "payload": "no"
            }
          ],
          [{"type": "callback", "text": "1", "payload": "1"},
           {"type": "callback", "text": "2", "payload": "2"},
           {"type": "callback", "text": "3", "payload": "3"},
           {"type": "callback", "text": "4", "payload": "4"},
           {"type": "callback", "text": "5", "payload": "5"},
           {"type": "callback", "text": "6", "payload": "6"},
           {"type": "callback", "text": "7", "payload": "7"}
          ]
        ]
      }
    }
  ]
}